### ISSUE TITLE
執行gh-ost 遇到錯誤

### ISSUE THREAD

**Issue by HaroldZhen** [lazzyfu/AuditSQL#137]
執行gh-ost遇到註解為中文的報錯問題
`'ascii' codec can't encode characters in position 343-348: ordinal not in range(128)`

**Comment by HaroldZhen** [comment]
解決辦法：
```
# 80端口為外部端口，可自行更改
# 8000為docker內部服務端口，8000端口不可改變
docker run -itd -p 80:8000  -e PYTHONIOENCODING=utf-8  -e LC_ALL='en_US.UTF-8' --name=sqlaudit 0a2b9265372d /bin/bash
```
或是 Dockfile 加上
```
ENV PYTHONIOENCODING=utf-8 LC_ALL en_US.UTF-8
```

**Comment by lazzyfu** [comment]
你好，中文是支持的，这个一直在用，应该是包含了ascii字符，明天方便把你的注释发我，我测试一下

发自我的 iPhone

**Comment by lazzyfu** [comment]
好的是支持utf8，支持中文注释的。一直在用，应该是你那包含了ascii，我明天测试一下。方便发我一下你的注释嘛？

发自我的 iPhone

**Comment by HaroldZhen** [comment]
出錯語法：
```
ALTER TABLE `hotel` ADD COLUMN `en_name` varchar(255) NOT NULL DEFAULT '' COMMENT '飯店英文名稱' AFTER `name`
```

**Comment by lazzyfu** [comment]
您好，我这边测试是OK的，请问题你数据库的字符集是utf8？或者你输入的ALTER语句包含了ASCII字符，谢谢。
![image](https://user-images.githubusercontent.com/14190782/48925951-76fd0080-ef04-11e8-9646-9201bd2b6212.png)

**Comment by HaroldZhen** [comment]
是的，資料庫字符集是utf8，語法就是只上面這樣
``` sql 
ALTER TABLE `hotel` ADD COLUMN `en_name` varchar(255) NOT NULL DEFAULT '' COMMENT '飯店英文名稱' AFTER `name`
```

**Comment by lazzyfu** [comment]
好的。我复制过来的，执行没问题，我模拟下加入ASCII字符，进行测试，并修正下，谢谢。如果有使用上的问题，请反馈，谢谢。如果有好的思路或者方法，也请反馈给我，感谢。

**Comment by lazzyfu** [comment]
你是加了：-e PYTHONIOENCODING=utf-8 这个解决的吗？
