### ISSUE TITLE
請問如何正確重啟Incecption

### ISSUE THREAD

**Issue by HaroldZhen** [lazzyfu/AuditSQL#138]
請問如何正確重啟Incecption?

kill -9 inception
./opt/inception/bin/Inception --defaults-file=/etc/inception.cnf &

**Comment by lazzyfu** [comment]
你的方法是对的，目前没有别的办法，inception大家都是这样重启的，现在inception的源码在git上已经被作者删除了，谢谢

**Comment by lazzyfu** [comment]
或者你用supervisor管理，我docker里面是用的supervisor管理的

**Comment by HaroldZhen** [comment]
這樣我是重啟supervisor就可以了吧！

順便一題，我使用你的docker為基礎，加上docker-compose來啟用。

**Comment by lazzyfu** [comment]
恩恩，可以的哈，这个你自己把握即可。我本月底发布新的优化版本，支持新的查询功能，感谢支持，谢谢
