### ISSUE TITLE
这个DML语句备份到底是怎么使用的

### ISSUE THREAD

**Issue by thb7758** [lazzyfu/AuditSQL#155]
DML语句执行成功，备份一直不可以。这个具体还需要怎么配置，他备份的的sql或者文件是存在那里

**Comment by lazzyfu** [comment]
你提交DML工单，执行，会自动生成备份语句
请参考：
https://github.com/lazzyfu/AuditSQL/wiki/sqlexecute

**Comment by lazzyfu** [comment]
建议更新到最新的代码，在试下
1.目标数据库要开启binlog
2.目标数据库要开启gtid
3.要有replication slave, replication client权限

**Comment by thb7758** [comment]
好的。我目前看到是 1和2我是已经做过了。我去定位下这个3是否有操作

**Comment by thb7758** [comment]
已经进群谢谢了

**Comment by lazzyfu** [comment]
有问题可以私聊我哈
