### ISSUE TITLE
按照文档部署，niginx报500

### ISSUE THREAD

**Issue by Ezail3** [lazzyfu/AuditSQL#177]
访问主页跳转到登陆后变成500
![image](https://user-images.githubusercontent.com/21214836/51246067-6c229180-19c4-11e9-8a45-67f206b97c11.png)
![image](https://user-images.githubusercontent.com/21214836/51246084-76dd2680-19c4-11e9-9115-8de361422f5b.png)

nginx没有错误日志没有内容，是否是最新代码登陆这块有问题，求指导，谢谢！！！

**Comment by lazzyfu** [comment]
你好，你是下载的docker还是自己部署的代码？若是自己部署，需要初始化很多数据。docker只需要启动服务即可使用

**Comment by lazzyfu** [comment]
如果使用docker，请检查下相关服务，uwsgi，nginx，redis，mysql等是否启动。或者检查下/data/web/sqlaudit/logs下面的日志输出，谢谢

**Comment by lazzyfu** [comment]
如果有问题可以加群哈

**Comment by Ezail3** [comment]
> 如果使用docker，请检查下相关服务，uwsgi，nginx，redis，mysql等是否启动。或者检查下/data/web/sqlaudit/logs下面的日志输出，谢谢

不好意思 mysql 没起来 我自己排查一下  谢谢指导 看那个all log看到了 谢谢哈
